sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tKcrhjGyZ6vfn9ccYyh
    access-key-secret: 0aTcgONqJVEYSJCDXtDeDOFXXAC6BE
    bucket-name: sky-yinhao
  redis:
    host: localhost
    port: 6379
    password: 123456
    datebase: 0
  wechat:
    appid: wxbf296758f58fb8dc
    secret: 358dbc1a9d40e3250b0245e0697cfe94
    mchid: 1
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url:
    api-v3-key:
    mch-serial-no:
    private-key-file-path: